[project]
name = "nanogpt"
version = "0.1.0"
description = "The simplest, fastest repository for training/finetuning medium-sized GPTs."
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
dependencies = [
    "torch",
    "numpy",
    "transformers",
    "datasets",
    "tiktoken",
    "wandb",
    "tqdm",
    "tensorboard",
    "plotly>=6.7.0",
    "anywidget>=0.9.21",
    "torchvision>=0.23.0",
    "ipycanvas>=0.14.3",
]

[project.optional-dependencies]
notebooks = [
    "jupyter",
    "ipywidgets",
    "anywidget",
    "ipycanvas>=0.13",
    "pillow",
    "jupyterlab-rise>=0.43",
    "torchviz>=0.0.2",
]

[tool.uv]
package = false
