_target_: configs.ModelConfig
# evaluate the base gpt2
# n_layer=24, n_head=16, n_embd=1024
# 350M parameters
n_layer: 24
n_head: 16
n_embd: 1024
batch_size: 4
block_size: 1024
dropout: 0.0
bias: false
vocab_size: null
